hmrc/income-tax-state-benefits-frontend

- app/actions/ActionsProvider.scala
- app/actions/EndOfYearFilterAction.scala
- app/controllers/jobseekers/JobSeekersAllowanceController.scala
- app/models/BenefitType.scala
- app/models/IncomeTaxUserData.scala
- app/models/pages/SummaryPage.scala
- app/models/pages/elements/BenefitSummaryListRowData.scala
- app/models/pages/jobseekers/JobSeekersAllowancePage.scala
- app/utils/InYearUtil.scala
- app/utils/ViewUtils.scala
- app/views/pages/SummaryPageView.scala.html
- app/views/pages/jobseekers/JobSeekersAllowancePageView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/jobseekers/JobSeekersAllowanceControllerISpec.scala
- project/AppDependencies.scala
- test/actions/ActionsProviderSpec.scala
- test/actions/EndOfYearFilterActionSpec.scala
- test/controllers/jobseekers/JobSeekersAllowanceControllerSpec.scala
- test/models/IncomeTaxUserDataSpec.scala
- test/models/pages/elements/BenefitSummaryListRowDataSpec.scala
- test/models/pages/jobseekers/JobSeekersAllowancePageSpec.scala
- test/support/builders/models/pages/SummaryPageBuilder.scala
- test/support/builders/models/pages/jobseekers/JobSeekersAllowancePageBuilder.scala
- test/support/builders/models/pages/jobseekers/elements/BenefitSummaryListRowDataBuilder.scala
- test/utils/InYearUtilSpec.scala
- test/utils/ViewUtilsSpec.scala
- test/views/pages/SummaryPageViewSpec.scala
- test/views/pages/jobseekers/JobSeekersAllowancePageViewSpec.scala
[SASS-3536](https://jira.tools.tax.service.gov.uk/browse/SASS-3536)
> SASS-3536 - Create Jobseeker's Allowance 'Add missing claim' page.

- app/controllers/jobseekers/DidClaimEndInTaxYearController.scala
- app/forms/YesNoForm.scala
- app/models/pages/jobseekers/DidClaimEndInTaxYearPage.scala
- app/views/pages/jobseekers/DidClaimEndInTaxYearPageView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/jobseekers/DidClaimEndInTaxYearControllerISpec.scala
- it/controllers/jobseekers/StartDateControllerISpec.scala
- test/controllers/jobseekers/DidClaimEndInTaxYearControllerSpec.scala
- test/forms/YesNoFormSpec.scala
- test/support/builders/pages/jobseekers/DidClaimEndInTaxYearPageBuilder.scala
- test/views/pages/jobseekers/DidClaimEndInTaxYearPageViewSpec.scala
[SASS-3592](https://jira.tools.tax.service.gov.uk/browse/SASS-3592)
> SASS-3592 main code for 'Did this claim end in the tax year?' page

- app/views/templates/Head.scala.html
- app/views/templates/Layout.scala.html
- conf/application.conf
[SASS-3691](https://jira.tools.tax.service.gov.uk/browse/SASS-3691)
> SASS-3691 Set CSP policy configuration

- app/models/ClaimCYAModel.scala
- app/models/StateBenefitsUserData.scala
- app/models/pages/jobseekers/DidClaimEndInTaxYearPage.scala
- app/models/pages/jobseekers/EndDatePage.scala
- app/models/pages/jobseekers/StartDatePage.scala
- app/views/pages/jobseekers/DidClaimEndInTaxYearPageView.scala.html
- test/models/StateBenefitsUserDataSpec.scala
- test/models/pages/jobseekers/StartDatePageSpec.scala
- test/support/builders/ClaimCYAModelBuilder.scala
- test/support/builders/StateBenefitsUserDataBuilder.scala
- test/views/pages/jobseekers/DidClaimEndInTaxYearPageViewSpec.scala
[SASS-3719](https://jira.tools.tax.service.gov.uk/browse/SASS-3719)
> SASS-3719 - Persist session data in MongoDB.

- .github/PULL_REQUEST_TEMPLATE.md
- app/views/pages/jobseekers/JobSeekersAllowancePageView.scala.html
- test/views/pages/jobseekers/JobSeekersAllowancePageViewSpec.scala
[SASS-3805](https://jira.tools.tax.service.gov.uk/browse/SASS-3805)
> SASS-3805 - FIX due to library upgrade.

- app/controllers/jobseekers/AmountController.scala
- app/controllers/jobseekers/TaxTakenOffController.scala
- app/forms/FormsProvider.scala
- app/models/pages/jobseekers/TaxTakenOffPage.scala
- app/services/ClaimService.scala
- app/views/pages/jobseekers/TaxTakenOffPageView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/jobseekers/TaxTakenOffControllerISpec.scala
- test/controllers/jobseekers/TaxTakenOffControllerSpec.scala
- test/forms/FormsProviderSpec.scala
- test/models/pages/jobseekers/TaxTakenOffPageSpec.scala
- test/services/ClaimServiceSpec.scala
- test/support/builders/pages/jobseekers/TaxTakenOffPageBuilder.scala
- test/support/mocks/MockClaimService.scala
- test/views/pages/jobseekers/DidClaimEndInTaxYearPageViewSpec.scala
- test/views/pages/jobseekers/TaxTakenOffPageViewSpec.scala
[SASS-3678](https://jira.tools.tax.service.gov.uk/browse/SASS-3678)
> SASS-3678 - Create 'Did you have tax taken off?' page.

- app/controllers/jobseekers/TaxTakenOffAmountController.scala
- app/controllers/jobseekers/TaxTakenOffController.scala
- app/forms/FormsProvider.scala
- app/models/pages/jobseekers/TaxTakenOffAmountPage.scala
- app/services/ClaimService.scala
- app/views/pages/jobseekers/AmountPageView.scala.html
- app/views/pages/jobseekers/TaxTakenOffAmountPageView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/jobseekers/TaxTakenOffAmountControllerISpec.scala
- test/controllers/jobseekers/TaxTakenOffAmountControllerSpec.scala
- test/models/pages/jobseekers/TaxTakenOffAmountPageSpec.scala
- test/services/ClaimServiceSpec.scala
- test/support/builders/pages/jobseekers/TaxTakenOffAmountPageBuilder.scala
- test/support/mocks/MockClaimService.scala
- test/views/pages/jobseekers/TaxTakenOffAmountPageViewSpec.scala
[SASS-3679](https://jira.tools.tax.service.gov.uk/browse/SASS-3679)
> SASS-3679 - Create 'How much tax was taken off?' page.

- app/controllers/jobseekers/ReviewClaimController.scala
- app/controllers/jobseekers/TaxTakenOffAmountController.scala
- app/controllers/jobseekers/TaxTakenOffController.scala
- app/models/pages/jobseekers/ReviewClaimPage.scala
- app/utils/ViewUtils.scala
- app/views/pages/jobseekers/ReviewClaimPageView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/jobseekers/ReviewClaimControllerISpec.scala
- it/controllers/jobseekers/TaxTakenOffControllerISpec.scala
- test/controllers/jobseekers/ReviewClaimControllerSpec.scala
- test/controllers/jobseekers/TaxTakenOffAmountControllerSpec.scala
- test/controllers/jobseekers/TaxTakenOffControllerSpec.scala
- test/models/pages/jobseekers/ReviewClaimPageSpec.scala
- test/support/builders/pages/jobseekers/ReviewClaimPageBuilder.scala
- test/support/helpers/ViewHelper.scala
- test/views/pages/jobseekers/ReviewClaimPageViewSpec.scala
[SASS-3681](https://jira.tools.tax.service.gov.uk/browse/SASS-3681)
> SASS-3681 add ReviewJobSeekersAllowanceClaim page

- app/actions/AuthorisedAction.scala
- it/support/stubs/WireMockStubs.scala
- test/actions/AuthorisedActionSpec.scala
- test/support/mocks/MockAuthorisationService.scala
- test/support/mocks/MockAuthorisedAction.scala
- test/support/mocks/MockAuthorisedActionCIS.scala
Increasing the minimum Confidence Level value to 250 rather than 200
[Add a link to the relevant story in Jira](https://jira.tools.tax.service.gov.uk/browse/SASS-3946)
SASS-CHANGE-3946 Increase the 'Confidence Level' to 250 from 200
> SASS-3946 Increase the 'Confidence Level' to 250 from 200

- app/views/pages/jobseekers/DidClaimEndInTaxYearPageView.scala.html
- app/views/pages/jobseekers/EndDatePageView.scala.html
- app/views/pages/jobseekers/JobSeekersAllowancePageView.scala.html
- app/views/pages/jobseekers/StartDatePageView.scala.html
- app/views/pages/jobseekers/TaxTakenOffPageView.scala.html
- app/views/templates/helpers/Caption.scala.html
- test/support/helpers/ViewHelper.scala
- test/views/pages/jobseekers/DidClaimEndInTaxYearPageViewSpec.scala
- test/views/pages/jobseekers/EndDatePageViewSpec.scala
- test/views/pages/jobseekers/StartDatePageViewSpec.scala
- test/views/pages/jobseekers/TaxTakenOffPageViewSpec.scala
- test/views/templates/helpers/CaptionSpec.scala
[SASS-3723](https://jira.tools.tax.service.gov.uk/browse/SASS-3723)
> SASS-3723 edit error message coverage in forms

- app/controllers/jobseekers/AmountController.scala
- app/controllers/jobseekers/DidClaimEndInTaxYearController.scala
- app/controllers/jobseekers/EndDateController.scala
- app/controllers/jobseekers/StartDateController.scala
- app/controllers/jobseekers/TaxTakenOffAmountController.scala
- app/controllers/jobseekers/TaxTakenOffController.scala
- app/models/ClaimCYAModel.scala
- app/models/StateBenefitsUserData.scala
- app/services/ClaimService.scala
- it/controllers/jobseekers/AmountControllerISpec.scala
- it/controllers/jobseekers/DidClaimEndInTaxYearControllerISpec.scala
- it/controllers/jobseekers/EndDateControllerISpec.scala
- it/controllers/jobseekers/StartDateControllerISpec.scala
- it/controllers/jobseekers/TaxTakenOffAmountControllerISpec.scala
- it/controllers/jobseekers/TaxTakenOffControllerISpec.scala
- test/controllers/jobseekers/AmountControllerSpec.scala
- test/controllers/jobseekers/DidClaimEndInTaxYearControllerSpec.scala
- test/controllers/jobseekers/EndDateControllerSpec.scala
- test/controllers/jobseekers/StartDateControllerSpec.scala
- test/controllers/jobseekers/TaxTakenOffAmountControllerSpec.scala
- test/controllers/jobseekers/TaxTakenOffControllerSpec.scala
- test/models/ClaimCYAModelSpec.scala
- test/models/StateBenefitsUserDataSpec.scala
- test/services/ClaimServiceSpec.scala
- test/support/mocks/MockClaimService.scala
[SASS-3901](https://jira.tools.tax.service.gov.uk/browse/SASS-3901)
> SASS-3901 - JSA end of year Customer data navigation.

- app/actions/ActionsProvider.scala
- app/controllers/jobseekers/JobSeekersAllowanceController.scala
- app/models/pages/jobseekers/JobSeekersAllowancePage.scala
- app/views/pages/jobseekers/JobSeekersAllowancePageView.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/SummaryControllerISpec.scala
- it/controllers/jobseekers/JobSeekersAllowanceControllerISpec.scala
- it/controllers/session/UserSessionDataControllerISpec.scala
- test/actions/ActionsProviderSpec.scala
- test/models/pages/jobseekers/JobSeekersAllowancePageSpec.scala
- test/support/builders/pages/jobseekers/JobSeekersAllowancePageBuilder.scala
- test/views/pages/jobseekers/JobSeekersAllowancePageViewSpec.scala
[SASS-3755](https://jira.tools.tax.service.gov.uk/browse/SASS-3755)
> SASS-3755 add the 'in year' version of JSA summary

- app/actions/ActionsProvider.scala
- app/actions/UserSessionDataRequestRefinerAction.scala
- app/views/templates/AgentAuthErrorPageView.scala.html
- app/views/templates/helpers/Button.scala.html
- project/AppDependencies.scala
- test/actions/UserSessionDataRequestRefinerActionSpec.scala
- test/controllers/jobseekers/AmountControllerSpec.scala
- test/controllers/jobseekers/EndDateControllerSpec.scala
- test/controllers/jobseekers/EndDateQuestionControllerSpec.scala
- test/controllers/jobseekers/StartDateControllerSpec.scala
- test/controllers/jobseekers/TaxPaidControllerSpec.scala
- test/controllers/jobseekers/TaxPaidQuestionControllerSpec.scala
[SASS-4099](https://jira.tools.tax.service.gov.uk/browse/SASS-4099)
> SASS-4099 - Enable Back button on State Benefits FE.

- app/controllers/jobseekers/SectionCompletedQuestionController.scala
- app/forms/jobseekers/FormsProvider.scala
- app/models/pages/jobseekers/SectionCompletedQuestionPage.scala
- app/views/pages/jobseekers/JobSeekersAllowancePageView.scala.html
- app/views/pages/jobseekers/SectionCompletedQuestionPageView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/jobseekers/SectionCompletedQuestionControllerISpec.scala
- test/controllers/jobseekers/SectionCompletedQuestionControllerSpec.scala
- test/forms/jobseekers/FormsProviderSpec.scala
- test/support/builders/pages/jobseekers/SectionCompletedQuestionPageBuilder.scala
- test/views/pages/jobseekers/JobSeekersAllowancePageViewSpec.scala
- test/views/pages/jobseekers/SectionCompletedQuestionPageViewSpec.scala
[SASS-3955](https://jira.tools.tax.service.gov.uk/browse/SASS-3955)
> SASS-3955 add 'have you completed this section?' page

- README.md
Update README.md file for State Benefits FE
[SASS-4100](https://jira.tools.tax.service.gov.uk/browse/SASS-4100)
> SASS-4100 - Update README.md file for State Benefits FE

- app/forms/jobseekers/FormsProvider.scala
- app/views/pages/jobseekers/AmountPageView.scala.html
- app/views/pages/jobseekers/EndDatePageView.scala.html
- app/views/pages/jobseekers/EndDateQuestionPageView.scala.html
- app/views/pages/jobseekers/JobSeekersAllowancePageView.scala.html
- app/views/pages/jobseekers/RemoveClaimPageView.scala.html
- app/views/pages/jobseekers/ReviewClaimPageView.scala.html
- app/views/pages/jobseekers/SectionCompletedQuestionPageView.scala.html
- app/views/pages/jobseekers/TaxPaidPageView.scala.html
- conf/messages
- conf/messages.cy
- project/build.properties
- test/config/MessagesSpec.scala
- test/forms/jobseekers/FormsProviderSpec.scala
[SASS-4112](https://jira.tools.tax.service.gov.uk/browse/SASS-4112)
> SASS-4112 - Add pages content for ESA to messages file.

- app/controllers/jobseekers/StartDateController.scala
- app/forms/jobseekers/FormsProvider.scala
- conf/messages
- conf/messages.cy
- test/views/pages/jobseekers/StartDatePageViewSpec.scala
[SASS-4014](https://jira.tools.tax.service.gov.uk/browse/SASS-4014)
> SASS-4014 do not allow the start date to be after the end date if it exists

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> Upgrades play-frontend-hmrc.

- app/views/pages/ClaimsPageView.scala.html
- test/views/pages/employmentsupport/ClaimsPageViewSpec.scala
- test/views/pages/jobseekers/ClaimsPageViewSpec.scala
[SASS-4296](https://jira.tools.tax.service.gov.uk/browse/SASS-4296)
> [Spike] Test commit

- app/views/pages/ClaimsPageView.scala.html
- test/views/pages/employmentsupport/ClaimsPageViewSpec.scala
- test/views/pages/jobseekers/ClaimsPageViewSpec.scala
This reverts commit 7bf4c2cff3a27f4b8c8a12d0d262dfc1244214d6.
> Revert "[Spike] Test commit"

- app/views/templates/helpers/Heading.scala.html
- test/support/helpers/ViewHelper.scala
- test/views/pages/employmentsupport/EndDatePageViewSpec.scala
- test/views/pages/employmentsupport/EndDateQuestionPageViewSpec.scala
- test/views/pages/employmentsupport/StartDatePageViewSpec.scala
- test/views/pages/employmentsupport/TaxPaidQuestionPageViewSpec.scala
- test/views/pages/jobseekers/EndDatePageViewSpec.scala
- test/views/pages/jobseekers/EndDateQuestionPageViewSpec.scala
- test/views/pages/jobseekers/StartDatePageViewSpec.scala
- test/views/pages/jobseekers/TaxPaidQuestionPageViewSpec.scala
- test/views/templates/helpers/HeadingSpec.scala
[SASS-4238](https://jira.tools.tax.service.gov.uk/browse/SASS-4238)
> SASS-4238 fix accessibility test issue - colour contrast

- app/controllers/AmountController.scala
- app/controllers/TaxPaidController.scala
- app/forms/AmountBoundaries.scala
- app/forms/AmountForm.scala
- app/forms/FormsProvider.scala
- app/forms/validation/mappings/Formatters.scala
- app/forms/validation/mappings/MappingUtil.scala
- conf/messages
- conf/messages.cy
- test/controllers/AmountControllerSpec.scala
- test/forms/AmountFormSpec.scala
- test/forms/FormsProviderSpec.scala
- test/models/pages/AmountPageSpec.scala
- test/support/builders/ClaimCYAModelBuilder.scala
- test/views/pages/employmentsupport/AmountPageViewSpec.scala
- test/views/pages/jobseekers/AmountPageViewSpec.scala
[SASS-4384](https://jira.tools.tax.service.gov.uk/browse/SASS-4384)
> SASS-4384 - Validation on the 'How much JSA did you get?'.

- app/controllers/EndDateController.scala
- app/forms/DateForm.scala
- app/forms/FormsProvider.scala
- app/forms/validation/mappings/MappingUtil.scala
- app/views/pages/EndDatePageView.scala.html
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- test/models/pages/EndDatePageSpec.scala
- test/views/pages/employmentsupport/EndDatePageViewSpec.scala
- test/views/pages/jobseekers/EndDatePageViewSpec.scala
[SASS-4295](https://jira.tools.tax.service.gov.uk/browse/SASS-4295)
> SASS-4295 - Error states for 'When did this claim end?' for ESA/JSA

- app/views/pages/ClaimsPageView.scala.html
- test/views/pages/employmentsupport/ClaimsPageViewSpec.scala
- test/views/pages/jobseekers/ClaimsPageViewSpec.scala
[SASS-4437](https://jira.tools.tax.service.gov.uk/browse/SASS-4437)
> SASS-4437 - Empty list of claims - colour of buttons.

- app/controllers/EndDateQuestionController.scala
- app/forms/FormsProvider.scala
- app/models/pages/EndDateQuestionPage.scala
- app/views/pages/EndDateQuestionPageView.scala.html
- app/views/pages/RemoveClaimPageView.scala.html
- app/views/pages/ReviewClaimPageView.scala.html
- conf/messages
- conf/messages.cy
- test/forms/FormsProviderSpec.scala
- test/models/pages/EndDateQuestionPageSpec.scala
- test/support/builders/pages/EndDateQuestionPageBuilder.scala
- test/views/pages/employmentsupport/EndDateQuestionPageViewSpec.scala
- test/views/pages/employmentsupport/RemoveClaimPageViewSpec.scala
- test/views/pages/employmentsupport/ReviewClaimPageViewSpec.scala
- test/views/pages/jobseekers/EndDateQuestionPageViewSpec.scala
- test/views/pages/jobseekers/RemoveClaimPageViewSpec.scala
- test/views/pages/jobseekers/ReviewClaimPageViewSpec.scala
[SASS-4459](https://jira.tools.tax.service.gov.uk/browse/SASS-4459)
> SASS-4459 update content for the end date question page

- app/controllers/AmountController.scala
- app/controllers/EndDateController.scala
- app/controllers/TaxPaidQuestionController.scala
- project/AppDependencies.scala
- test/controllers/AmountControllerSpec.scala
- test/controllers/EndDateControllerSpec.scala
- test/controllers/TaxPaidQuestionControllerSpec.scala
[SASS-4460](https://jira.tools.tax.service.gov.uk/browse/SASS-4460)
> SASS-4460 - Change JSA/ESA page order

- app/views/pages/EndDatePageView.scala.html
- app/views/pages/StartDatePageView.scala.html
- conf/messages
- conf/messages.cy
- test/views/pages/employmentsupport/EndDatePageViewSpec.scala
- test/views/pages/employmentsupport/StartDatePageViewSpec.scala
- test/views/pages/jobseekers/EndDatePageViewSpec.scala
- test/views/pages/jobseekers/StartDatePageViewSpec.scala
[SASS-4469](https://jira.tools.tax.service.gov.uk/browse/SASS-4469)
> SASS-4469 - Dynamic example dates.

- app/views/pages/ReviewClaimPageView.scala.html
- test/views/pages/employmentsupport/ReviewClaimPageViewSpec.scala
- test/views/pages/jobseekers/ReviewClaimPageViewSpec.scala
[SASS-4485](https://jira.tools.tax.service.gov.uk/browse/SASS-4485)
> SASS-4485 - New CYA page ordering.

- app/controllers/AmountController.scala
- app/forms/FormsProvider.scala
- app/views/pages/EndDatePageView.scala.html
- app/views/pages/EndDateQuestionPageView.scala.html
- conf/messages
- conf/messages.cy
- test/forms/FormsProviderSpec.scala
- test/models/StateBenefitsUserDataSpec.scala
- test/models/pages/AmountPageSpec.scala
- test/support/builders/pages/AmountPageBuilder.scala
- test/views/pages/employmentsupport/AmountPageViewSpec.scala
- test/views/pages/employmentsupport/EndDatePageViewSpec.scala
- test/views/pages/employmentsupport/StartDatePageViewSpec.scala
- test/views/pages/employmentsupport/TaxPaidPageViewSpec.scala
- test/views/pages/jobseekers/AmountPageViewSpec.scala
- test/views/pages/jobseekers/EndDatePageViewSpec.scala
- test/views/pages/jobseekers/StartDatePageViewSpec.scala
- test/views/pages/jobseekers/TaxPaidPageViewSpec.scala
[SASS-4468](https://jira.tools.tax.service.gov.uk/browse/SASS-4468)
> SASS-4468 - New error states for JSA/ESA

- app/forms/DateForm.scala
- app/forms/FormsProvider.scala
- app/utils/ViewUtils.scala
- app/views/pages/EndDateQuestionPageView.scala.html
- app/views/pages/RemoveClaimPageView.scala.html
- app/views/pages/ReviewClaimPageView.scala.html
- conf/messages
- conf/messages.cy
- test/forms/FormsProviderSpec.scala
- test/utils/InYearUtilSpec.scala
- test/utils/ViewUtilsSpec.scala
- test/views/pages/employmentsupport/AmountPageViewSpec.scala
- test/views/pages/employmentsupport/EndDatePageViewSpec.scala
- test/views/pages/employmentsupport/EndDateQuestionPageViewSpec.scala
- test/views/pages/employmentsupport/RemoveClaimPageViewSpec.scala
- test/views/pages/employmentsupport/ReviewClaimPageViewSpec.scala
- test/views/pages/employmentsupport/StartDatePageViewSpec.scala
- test/views/pages/employmentsupport/TaxPaidPageViewSpec.scala
- test/views/pages/employmentsupport/TaxPaidQuestionPageViewSpec.scala
- test/views/pages/jobseekers/AmountPageViewSpec.scala
- test/views/pages/jobseekers/EndDatePageViewSpec.scala
- test/views/pages/jobseekers/EndDateQuestionPageViewSpec.scala
- test/views/pages/jobseekers/RemoveClaimPageViewSpec.scala
- test/views/pages/jobseekers/ReviewClaimPageViewSpec.scala
- test/views/pages/jobseekers/StartDatePageViewSpec.scala
- test/views/pages/jobseekers/TaxPaidPageViewSpec.scala
- test/views/pages/jobseekers/TaxPaidQuestionPageViewSpec.scala
[SASS-4471](https://jira.tools.tax.service.gov.uk/browse/SASS-4471)
> SASS-4471 - All dates must be on one line.

- project/AppDependencies.scala
> Bump uk.gov.hmrc: play-frontend-hmrc to 6.8.0-play-28

- app/actions/ActionsProvider.scala
- app/actions/ViewStateBenefitsAuditAction.scala
- app/controllers/ClaimsController.scala
- app/models/audit/AmendStateBenefitAudit.scala
- app/models/audit/AuditModel.scala
- app/models/audit/BenefitData.scala
- app/models/audit/BenefitDetails.scala
- app/models/audit/CreateStateBenefitAudit.scala
- app/models/audit/IgnoreStateBenefitAudit.scala
- app/models/audit/RemoveStateBenefitAudit.scala
- app/models/audit/UnIgnoreStateBenefitAudit.scala
- app/models/audit/ViewStateBenefitAudit.scala
- app/models/audit/ViewStateBenefitsAudit.scala
- app/services/AuditService.scala
- test/actions/ActionsProviderSpec.scala
- test/actions/ViewStateBenefitsAuditActionSpec.scala
- test/controllers/ClaimsControllerSpec.scala
- test/models/audit/BenefitDataSpec.scala
- test/models/audit/ViewStateBenefitsAuditSpec.scala
- test/services/AuditServiceSpec.scala
- test/support/builders/audit/BenefitDataBuilder.scala
- test/support/builders/audit/ViewStateBenefitsAuditBuilder.scala
- test/support/mocks/MockActionsProvider.scala
- test/support/mocks/MockAuditConnector.scala
- test/support/mocks/MockAuditService.scala
- test/support/mocks/MockConfiguration.scala
[SASS-4651](https://jira.tools.tax.service.gov.uk/browse/SASS-4651)
> SASS-4651 - View State Benefits - audit details.

- app/controllers/RemoveClaimController.scala
- app/controllers/ReviewClaimController.scala
- app/models/audit/BenefitDetails.scala
- app/models/audit/IgnoreStateBenefitAudit.scala
- app/models/audit/UnIgnoreStateBenefitAudit.scala
- app/services/StateBenefitsService.scala
- test/controllers/RemoveClaimControllerSpec.scala
- test/controllers/ReviewClaimControllerSpec.scala
- test/models/audit/BenefitDetailsSpec.scala
- test/models/audit/IgnoreStateBenefitAuditSpec.scala
- test/models/audit/UnIgnoreStateBenefitAuditSpec.scala
- test/services/StateBenefitsServiceSpec.scala
- test/support/builders/audit/IgnoreStateBenefitAuditBuilder.scala
- test/support/builders/audit/UnIgnoreStateBenefitAuditBuilder.scala
- test/support/mocks/MockStateBenefitsService.scala
[SASS-4654](https://jira.tools.tax.service.gov.uk/browse/SASS-4654)
> SASS-4654 - Ignore state benefit & Unignore state benefit.

- app/actions/ActionsProvider.scala
- app/actions/ViewStateBenefitAuditAction.scala
- app/controllers/ReviewClaimController.scala
- app/models/StateBenefitsUserData.scala
- app/models/audit/CreateStateBenefitAudit.scala
- app/models/audit/ViewStateBenefitAudit.scala
- app/services/StateBenefitsService.scala
- test/actions/ActionsProviderSpec.scala
- test/actions/ViewStateBenefitAuditActionSpec.scala
- test/controllers/ReviewClaimControllerSpec.scala
- test/models/StateBenefitsUserDataSpec.scala
- test/models/audit/CreateStateBenefitAuditSpec.scala
- test/models/audit/ViewStateBenefitAuditSpec.scala
- test/services/StateBenefitsServiceSpec.scala
- test/support/mocks/MockActionsProvider.scala
- test/support/mocks/MockStateBenefitsService.scala
[SASS-4652](https://jira.tools.tax.service.gov.uk/browse/SASS-4652)
> SASS-4652 - View state benefit & Create state benefit.

- app/controllers/ReviewClaimController.scala
- app/models/audit/AmendStateBenefitAudit.scala
- app/models/audit/RemoveStateBenefitAudit.scala
- app/services/StateBenefitsService.scala
- test/controllers/ReviewClaimControllerSpec.scala
- test/models/audit/AmendStateBenefitAuditSpec.scala
- test/models/audit/RemoveStateBenefitAuditSpec.scala
- test/services/StateBenefitsServiceSpec.scala
- test/support/builders/audit/RemoveStateBenefitAuditBuilder.scala
- test/support/mocks/MockStateBenefitsService.scala
[SASS-4653](https://jira.tools.tax.service.gov.uk/browse/SASS-4653)
> SASS-4653 - Amend state benefit & Remove state benefit.

- app/models/audit/AmendStateBenefitAudit.scala
- app/services/StateBenefitsService.scala
- it/controllers/ReviewClaimControllerISpec.scala
- test/services/StateBenefitsServiceSpec.scala
> FIX - audits prior data too.

- app/forms/DateForm.scala
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/views/pages/employmentsupport/ClaimsPageViewSpec.scala
- test/views/pages/employmentsupport/EndDatePageViewSpec.scala
- test/views/pages/employmentsupport/StartDatePageViewSpec.scala
- test/views/pages/jobseekers/ClaimsPageViewSpec.scala
- test/views/pages/jobseekers/EndDatePageViewSpec.scala
- test/views/pages/jobseekers/StartDatePageViewSpec.scala
[SASS-4700](https://jira.tools.tax.service.gov.uk/browse/SASS-4700)
> SASS-4700 - Implement 4 digit error code for Employment & State Benefits

- test/views/pages/employmentsupport/ClaimsPageViewSpec.scala
- test/views/pages/jobseekers/ClaimsPageViewSpec.scala
> [NO-TICKET] Fix test failures caused by new tax year

- app/models/pages/ClaimsPage.scala
- test/models/pages/ClaimsPageSpec.scala
[SASS-4540](https://jira.tools.tax.service.gov.uk/browse/SASS-4540)
> SASS-4540 Hide HMRC data item, when it has a customer override (Claim Page)

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
[SASS-5215](https://jira.tools.tax.service.gov.uk/browse/SASS-5215)
> SASS-5215: Content security policy violation fix

- app/views/pages/ReviewClaimPageView.scala.html
[SASS-4992](https://jira.tools.tax.service.gov.uk/browse/SASS-4992)
> SASS-4992 fix dates slipping onto the next row

- app/views/templates/helpers/InputText.scala.html
[SASS-5213](https://jira.tools.tax.service.gov.uk/browse/SASS-5213)
> SASS-5213 Remove the maxlength attribute from all text inputs only perform server-side validation when the form is submitted

- app/forms/DateForm.scala
- app/forms/DateFormData.scala
- test/forms/DateFormDataSpec.scala
- test/forms/DateFormSpec.scala
[SASS-5214](https://jira.tools.tax.service.gov.uk/browse/SASS-5214)
> SASS-5214 Date input not allowing user to add spaces between digits

- build.sbt
- conf/application.conf
- conf/prod.routes
- it/support/IntegrationTest.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
Whilst looking to see if NRS had been implemented in this microservice -  dependencies were upgraded.
Work undertaken was related to tickets - SASS-6639, SASS-6640, SASS-6641
> SASS-6639: Removed mock NRS url and Upgraded Dependencies

- project/AppDependencies.scala
> SASS-7277: Upgrade play-frontend-hmrc-play

- app/views/pages/ClaimsPageView.scala.html
- conf/messages
- conf/messages.cy
> SASS-7203: Add text for employment and journey allowance

- app/views/pages/ClaimsPageView.scala.html
- app/views/pages/RemoveClaimPageView.scala.html
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/views/pages/employmentsupport/ClaimsPageViewSpec.scala
- test/views/pages/jobseekers/ClaimsPageViewSpec.scala
> SASS-8274: Add Inset for removed claims AND add Warning message when the user is removing the claims

- app/controllers/ClaimsController.scala
- app/forms/FormsProvider.scala
- app/models/User.scala
- app/models/pages/ClaimsPage.scala
- app/views/pages/ClaimsPageView.scala.html
- app/views/templates/helpers/InputRadio.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/config/MessagesSpec.scala
- test/controllers/ClaimsControllerSpec.scala
- test/models/pages/ClaimsPageSpec.scala
- test/support/builders/pages/ClaimsPageBuilder.scala
- test/views/pages/employmentsupport/ClaimsPageViewSpec.scala
- test/views/pages/jobseekers/ClaimsPageViewSpec.scala
> SASS-8503: [accessibility] Add missing claim button

- app/controllers/SectionCompletedStateController.scala
Minor change to add journey name in dashed format to fix issue with status not being updated correctly
> SASS-10387 Added journeyName function

- app/actions/AuthorisedAction.scala
- app/config/AppConfig.scala
- app/config/Module.scala
- app/models/User.scala
- app/models/authorisation/Enrolment.scala
- conf/application.conf
- test/actions/AuthorisedActionSpec.scala
- test/controllers/SectionCompletedStateControllerSpec.scala
- test/support/mocks/MockAppConfig.scala
- test/support/stubs/AppConfigStub.scala
- **SASS-10602: Add EMA feature switch config item and refactor app config into trait -> class implementation**
- **SASS-10602: Add EMA implementation and associated test changes**
> SASS 10602

- test/controllers/SectionCompletedStateControllerSpec.scala
Moves mock to above result, so that the mock is executed before the result is executed.
[SASS-10761](https://jira.tools.tax.service.gov.uk/browse/SASS-10761)
> [SASS-10761] Move mocks to before the result executes

- conf/application.conf
> SASS-11943 Remove CSPFilter
